[profile.default]
src = "src"
out = "out"
test = "test"
solc = "0.8.27"
evm_version = "cancun"
bytecode_hash = "none"
cbor_metadata = false

# do not compile or test *.t.sol artifacts copied into the swiftpm build
no_match_path = "./test/Acceptance/{.index-build,.build}/**"

libs = ["./lib"]

[profile.ir]
via_ir = true
# TODO: optimizer is turned to false to ignore stack too deep issues
optimizer = false
optimizer_runs = 100000000

[fmt]
ignore = ["src/vendor/**/*"]
